/**
 * Build script для серверных модулей
 * Объединяет все server/*.gs файлы в один bundle для деплоя
 */

const fs = require('fs');
const path = require('path');

const SERVER_DIR = path.join(__dirname, '..', 'server');
const DIST_DIR = path.join(__dirname, '..', 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'server-bundle.gs');

console.log('🚀 Building server bundle...');

// Создаём dist директорию
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
  console.log('  ✓ Created dist/ directory');
}

// Порядок загрузки модулей (важно для зависимостей)
const modules = [
  'utils.gs',              // 1. Базовые утилиты (без зависимостей)
  'server.gs',             // 2. Константы и главный entry point
  'license-service.gs',    // 3. Лицензии
  'bindings-service.gs',   // 4. Связки
  'published-sheets-service.gs', // 5. Работа с листами
  'vk-api.gs',             // 6a. VK API вызовы
  'vk-posts.gs',           // 6b. Форматирование постов
  'vk-media.gs',           // 6c. Обработка медиа
  'telegram-service.gs',   // 7. Telegram API
  'posting-service.gs'     // 8. Публикация (зависит от всех)
];

let bundle = '// VK→Telegram Crossposter - Server Bundle\n';
bundle += '// Auto-generated by glasp/deploy-server.js\n';
bundle += `// Build date: ${new Date().toISOString()}\n`;
bundle += `// Version: 6.1\n\n`;

let totalLines = 0;
let includedModules = 0;

modules.forEach(module => {
  const filePath = path.join(SERVER_DIR, module);
  
  if (fs.existsSync(filePath)) {
    console.log(`  ✓ Including ${module}`);
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n').length;
    totalLines += lines;
    includedModules++;
    
    bundle += `\n// ============================================\n`;
    bundle += `// MODULE: ${module} (${lines} lines)\n`;
    bundle += `// ============================================\n\n`;
    bundle += content + '\n';
    
    console.log(`    Lines: ${lines}`);
  } else {
    console.warn(`  ⚠ Warning: ${module} not found, skipping`);
  }
});

fs.writeFileSync(OUTPUT_FILE, bundle, 'utf8');

console.log('\n✅ Server bundle created successfully!');
console.log(`📦 Output: ${OUTPUT_FILE}`);
console.log(`📊 Statistics:`);
console.log(`   - Modules included: ${includedModules}/${modules.length}`);
console.log(`   - Total lines: ${totalLines}`);
console.log(`   - Bundle size: ${Math.round(bundle.length / 1024)} KB`);

if (includedModules < modules.length) {
  console.warn('\n⚠️  Warning: Some modules were not found!');
  process.exit(1);
}