/**
 * Build script для клиентских модулей
 * Объединяет все client/*.gs файлы в один bundle для деплоя
 */

const fs = require('fs');
const path = require('path');

const CLIENT_DIR = path.join(__dirname, '..', 'client');
const DIST_DIR = path.join(__dirname, '..', 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'client-bundle.gs');

console.log('🚀 Building client bundle...');

// Создаём dist директорию
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
  console.log('  ✓ Created dist/ directory');
}

// Порядок загрузки модулей
const modules = [
  'client-core.gs',   // Константы, меню, логирование
  'client-dev.gs'     // API вызовы, тесты
];

let bundle = '// VK→Telegram Crossposter - Client Bundle\n';
bundle += '// Auto-generated by glasp/deploy-client.js\n';
bundle += `// Build date: ${new Date().toISOString()}\n`;
bundle += `// Version: 6.1\n\n`;

let totalLines = 0;
let includedModules = 0;

modules.forEach(module => {
  const filePath = path.join(CLIENT_DIR, module);
  
  if (fs.existsSync(filePath)) {
    console.log(`  ✓ Including ${module}`);
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n').length;
    totalLines += lines;
    includedModules++;
    
    bundle += `\n// ============================================\n`;
    bundle += `// MODULE: ${module} (${lines} lines)\n`;
    bundle += `// ============================================\n\n`;
    bundle += content + '\n';
    
    console.log(`    Lines: ${lines}`);
  } else {
    console.warn(`  ⚠ Warning: ${module} not found, skipping`);
  }
});

fs.writeFileSync(OUTPUT_FILE, bundle, 'utf8');

console.log('\n✅ Client bundle created successfully!');
console.log(`📦 Output: ${OUTPUT_FILE}`);
console.log(`📊 Statistics:`);
console.log(`   - Modules included: ${includedModules}/${modules.length}`);
console.log(`   - Total lines: ${totalLines}`);
console.log(`   - Bundle size: ${Math.round(bundle.length / 1024)} KB`);

if (includedModules < modules.length) {
  console.warn('\n⚠️  Warning: Some modules were not found!');
  process.exit(1);
}